#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef DRIVEKITDBTRIPACCESSMODULE_SWIFT_H
#define DRIVEKITDBTRIPACCESSMODULE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DriveKitDBTripAccessModule",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("DBAdvancedEnergyEstimation")
@interface DBAdvancedEnergyEstimation : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class DBTrip;

@interface DBAdvancedEnergyEstimation (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t contextId;
@property (nonatomic) double distance;
@property (nonatomic) double duration;
@property (nonatomic) double energy;
@property (nonatomic) double energyConsumption;
@property (nonatomic) double energyOpti;
@property (nonatomic) double energyOptiConsumption;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBBrakeWear")
@interface DBBrakeWear : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBBrakeWear (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t frontBrakeAutonomy;
@property (nonatomic) int32_t frontBrakeDistance;
@property (nonatomic) int32_t frontBrakePadWear;
@property (nonatomic) int32_t frontBrakeTotalWear;
@property (nonatomic) int32_t frontBrakeWearRate;
@property (nonatomic) int32_t rearBrakeAutonomy;
@property (nonatomic) int32_t rearBrakeDistance;
@property (nonatomic) int32_t rearBrakePadWear;
@property (nonatomic) int32_t rearBrakeTotalWear;
@property (nonatomic) int32_t rearBrakeWearRate;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBCall")
@interface DBCall : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class NSString;

@interface DBCall (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable audioInput;
@property (nonatomic, copy) NSString * _Nullable audioName;
@property (nonatomic, copy) NSString * _Nullable audioOutput;
@property (nonatomic, copy) NSString * _Nullable audioSystemValue;
@property (nonatomic) int32_t bluetoothClass;
@property (nonatomic) int32_t distance;
@property (nonatomic) int16_t distancePercent;
@property (nonatomic) int32_t duration;
@property (nonatomic) int16_t durationPercent;
@property (nonatomic) double end;
@property (nonatomic) int32_t id;
@property (nonatomic) BOOL isForbidden;
@property (nonatomic) double start;
@property (nonatomic, copy) NSString * _Nullable typeValue;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBCondition")
@interface DBCondition : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class DBManualTrip;

@interface DBCondition (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int16_t context;
@property (nonatomic) BOOL dayTimeTrip;
@property (nonatomic) int16_t weather;
@property (nonatomic) BOOL weekDay;
@property (nonatomic, strong) DBManualTrip * _Nullable trip;
@end


SWIFT_CLASS_NAMED("DBDeclaredTransportationMode")
@interface DBDeclaredTransportationMode : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBDeclaredTransportationMode (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic) BOOL passenger;
@property (nonatomic) int32_t transportationMode;
@property (nonatomic, strong) DBTrip * _Nullable trip;
@end


SWIFT_CLASS_NAMED("DBDriverDistraction")
@interface DBDriverDistraction : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class NSNumber;

@interface DBDriverDistraction (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) double distancePercentUnlock;
@property (nonatomic) double distanceUnlock;
@property (nonatomic) double durationPercentUnlock;
@property (nonatomic) double durationUnlock;
@property (nonatomic) int32_t nbUnlock;
@property (nonatomic) double score;
@property (nonatomic, strong) NSNumber * _Nullable scoreCallNumber;
@property (nonatomic, strong) NSNumber * _Nullable scoreUnlockNumber;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBEcoDriving")
@interface DBEcoDriving : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBEcoDriving (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t energyClass;
@property (nonatomic) double score;
@property (nonatomic) double scoreAccel;
@property (nonatomic) double scoreDecel;
@property (nonatomic) double scoreMain;
@property (nonatomic) double stdDevAccel;
@property (nonatomic) double stdDevDecel;
@property (nonatomic) double stdDevMain;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBEcoDrivingContext")
@interface DBEcoDrivingContext : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBEcoDrivingContext (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t contextId;
@property (nonatomic) double distance;
@property (nonatomic) double duration;
@property (nonatomic) double efficiencyScore;
@property (nonatomic) double scoreAccel;
@property (nonatomic) double scoreDecel;
@property (nonatomic) double scoreMain;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBEnergyEstimation")
@interface DBEnergyEstimation : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBEnergyEstimation (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) double energy;
@property (nonatomic) double energyConsumption;
@property (nonatomic) double energyOpti;
@property (nonatomic) double energyOptiConsumption;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBEvaluation")
@interface DBEvaluation : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface DBEvaluation (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic) int32_t evaluation;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBFuelEstimation")
@interface DBFuelEstimation : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBFuelEstimation (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) double co2Emission;
@property (nonatomic) double co2Mass;
@property (nonatomic) double coldFuelVolume;
@property (nonatomic) BOOL engineTempStatus;
@property (nonatomic) double fuelConsumption;
@property (nonatomic) double fuelVolume;
@property (nonatomic) double idleCo2Emission;
@property (nonatomic) double idleCo2Mass;
@property (nonatomic) double idleFuelConsumption;
@property (nonatomic) double idleFuelPercentage;
@property (nonatomic) double idleFuelVolume;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBFuelEstimationContext")
@interface DBFuelEstimationContext : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBFuelEstimationContext (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) double co2Emission;
@property (nonatomic) double co2Mass;
@property (nonatomic) int32_t contextId;
@property (nonatomic) double distance;
@property (nonatomic) double duration;
@property (nonatomic) double fuelConsumption;
@property (nonatomic) double fuelVolume;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBInformation")
@interface DBInformation : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class NSDate;

@interface DBInformation (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable arrivalAddress;
@property (nonatomic, copy) NSString * _Nullable arrivalCity;
@property (nonatomic) double arrivalLatitude;
@property (nonatomic) double arrivalLongitude;
@property (nonatomic, copy) NSString * _Nullable departureAddress;
@property (nonatomic, copy) NSString * _Nullable departureCity;
@property (nonatomic) double departureLatitude;
@property (nonatomic) double departureLongitude;
@property (nonatomic) double distance;
@property (nonatomic) int32_t duration;
@property (nonatomic, copy) NSDate * _Nullable startDate;
@property (nonatomic, strong) DBManualTrip * _Nullable trip;
@end


SWIFT_CLASS_NAMED("DBLogbook")
@interface DBLogbook : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBLogbook (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t status;
@property (nonatomic, copy) NSDate * _Nullable updateDate;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBManeuver")
@interface DBManeuver : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface DBManeuver (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t nbAngledParkings;
@property (nonatomic) int32_t nbBayParkings;
@property (nonatomic) int32_t nbCurveReverseDrivings;
@property (nonatomic) int32_t nbEmergencyStops;
@property (nonatomic) int32_t nbHillStarts;
@property (nonatomic) int32_t nbParallelParkings;
@property (nonatomic) int32_t nbRoundAbouts;
@property (nonatomic) int32_t nbStraightReverseDrivings;
@property (nonatomic) int32_t nbTurns;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBManualEvaluation")
@interface DBManualEvaluation : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBManualEvaluation (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic) int32_t evaluation;
@property (nonatomic, strong) DBManualTrip * _Nullable trip;
@end


SWIFT_CLASS_NAMED("DBManualManeuver")
@interface DBManualManeuver : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBManualManeuver (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t nbAngledParkings;
@property (nonatomic) int32_t nbBayParkings;
@property (nonatomic) int32_t nbCurveReverseDrivings;
@property (nonatomic) int32_t nbEmergencyStops;
@property (nonatomic) int32_t nbHillStarts;
@property (nonatomic) int32_t nbParallelParkings;
@property (nonatomic) int32_t nbRoundAbouts;
@property (nonatomic) int32_t nbStraightReverseDrivings;
@property (nonatomic) int32_t nbTurns;
@property (nonatomic, strong) DBManualTrip * _Nullable trip;
@end


SWIFT_CLASS_NAMED("DBManualTrip")
@interface DBManualTrip : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface DBManualTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable tripId;
@property (nonatomic, strong) DBCondition * _Nullable condition;
@property (nonatomic, strong) DBManualEvaluation * _Nullable evaluation;
@property (nonatomic, strong) DBInformation * _Nullable information;
@property (nonatomic, strong) DBManualManeuver * _Nullable maneuver;
@end


SWIFT_CLASS_NAMED("DBPollutants")
@interface DBPollutants : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBPollutants (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) double co;
@property (nonatomic) double hc;
@property (nonatomic) double nox;
@property (nonatomic) double soot;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBRoute")
@interface DBRoute : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class NSArray;

@interface DBRoute (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, strong) NSArray * _Nullable callIndex;
@property (nonatomic, strong) NSArray * _Nullable callTime;
@property (nonatomic, copy) NSString * _Nullable itinId;
@property (nonatomic, strong) NSArray * _Nullable latitude;
@property (nonatomic, strong) NSArray * _Nullable longitude;
@property (nonatomic, strong) NSArray * _Nullable screenLockedIndex;
@property (nonatomic, strong) NSArray * _Nullable screenLockedTime;
@property (nonatomic, strong) NSArray * _Nullable screenStatus;
@property (nonatomic, strong) NSArray * _Nullable speedingIndex;
@property (nonatomic, strong) NSArray * _Nullable speedingTime;
@end


SWIFT_CLASS_NAMED("DBSafety")
@interface DBSafety : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBSafety (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t nbAccel;
@property (nonatomic) int32_t nbAccelCrit;
@property (nonatomic) int32_t nbAdh;
@property (nonatomic) int32_t nbAdhCrit;
@property (nonatomic) int32_t nbDecel;
@property (nonatomic) int32_t nbDecelCrit;
@property (nonatomic) double safetyScore;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBSafetyContext")
@interface DBSafetyContext : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBSafetyContext (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t contextId;
@property (nonatomic) double distance;
@property (nonatomic) double duration;
@property (nonatomic) int32_t nbAccel;
@property (nonatomic) int32_t nbAccelCrit;
@property (nonatomic) int32_t nbAdh;
@property (nonatomic) int32_t nbAdhCrit;
@property (nonatomic) int32_t nbDecel;
@property (nonatomic) int32_t nbDecelCrit;
@property (nonatomic) double safetyScore;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBSafetyEvents")
@interface DBSafetyEvents : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBSafetyEvents (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) double distance;
@property (nonatomic) double elevation;
@property (nonatomic) double heading;
@property (nonatomic) double latitude;
@property (nonatomic) int32_t level;
@property (nonatomic) double longitude;
@property (nonatomic) double time;
@property (nonatomic) int32_t type;
@property (nonatomic) double value;
@property (nonatomic) double velocity;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBSpeedLimitContext")
@interface DBSpeedLimitContext : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBSpeedLimitContext (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t distance;
@property (nonatomic) int32_t duration;
@property (nonatomic) double score;
@property (nonatomic) int32_t speedingDistance;
@property (nonatomic) int32_t speedingDuration;
@property (nonatomic) int32_t speedLimit;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBSpeedingStatistics")
@interface DBSpeedingStatistics : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBSpeedingStatistics (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t distance;
@property (nonatomic) int32_t duration;
@property (nonatomic) double score;
@property (nonatomic) int32_t speedingDistance;
@property (nonatomic) int32_t speedingDuration;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBTireWear")
@interface DBTireWear : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBTireWear (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t frontTireAutonomy;
@property (nonatomic) int32_t frontTireDistance;
@property (nonatomic) int32_t frontTireTotalWear;
@property (nonatomic) int32_t frontTireWear;
@property (nonatomic) int32_t frontTireWearRate;
@property (nonatomic) int32_t rearTireAutonomy;
@property (nonatomic) int32_t rearTireDistance;
@property (nonatomic) int32_t rearTireTotalWear;
@property (nonatomic) int32_t rearTireWear;
@property (nonatomic) int32_t rearTireWearRate;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBTrip")
@interface DBTrip : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@class DBTripAdvice;
@class NSSet;

@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addTripAdvicesObject:(DBTripAdvice * _Nonnull)value;
- (void)removeTripAdvicesObject:(DBTripAdvice * _Nonnull)value;
- (void)addTripAdvices:(NSSet * _Nonnull)values;
- (void)removeTripAdvices:(NSSet * _Nonnull)values;
@end


@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addSpeedLimitContextsObject:(DBSpeedLimitContext * _Nonnull)value;
- (void)removeSpeedLimitContextsObject:(DBSpeedLimitContext * _Nonnull)value;
- (void)addSpeedLimitContexts:(NSSet * _Nonnull)values;
- (void)removeSpeedLimitContexts:(NSSet * _Nonnull)values;
@end


@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addSafetyEventsObject:(DBSafetyEvents * _Nonnull)value;
- (void)removeSafetyEventsObject:(DBSafetyEvents * _Nonnull)value;
- (void)addSafetyEvents:(NSSet * _Nonnull)values;
- (void)removeSafetyEvents:(NSSet * _Nonnull)values;
@end


@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addSafetyContextsObject:(DBSafetyContext * _Nonnull)value;
- (void)removeSafetyContextsObject:(DBSafetyContext * _Nonnull)value;
- (void)addSafetyContexts:(NSSet * _Nonnull)values;
- (void)removeSafetyContexts:(NSSet * _Nonnull)values;
@end


@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addFuelEstimationContextsObject:(DBFuelEstimationContext * _Nonnull)value;
- (void)removeFuelEstimationContextsObject:(DBFuelEstimationContext * _Nonnull)value;
- (void)addFuelEstimationContexts:(NSSet * _Nonnull)values;
- (void)removeFuelEstimationContexts:(NSSet * _Nonnull)values;
@end


@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addEcoDrivingContextsObject:(DBEcoDrivingContext * _Nonnull)value;
- (void)removeEcoDrivingContextsObject:(DBEcoDrivingContext * _Nonnull)value;
- (void)addEcoDrivingContexts:(NSSet * _Nonnull)values;
- (void)removeEcoDrivingContexts:(NSSet * _Nonnull)values;
@end


@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addAdvancedEnergyEstimationObject:(DBAdvancedEnergyEstimation * _Nonnull)value;
- (void)removeAdvancedEnergyEstimationObject:(DBAdvancedEnergyEstimation * _Nonnull)value;
- (void)addAdvancedEnergyEstimation:(NSSet * _Nonnull)values;
- (void)removeAdvancedEnergyEstimation:(NSSet * _Nonnull)values;
@end


@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addCallsObject:(DBCall * _Nonnull)value;
- (void)removeCallsObject:(DBCall * _Nonnull)value;
- (void)addCalls:(NSSet * _Nonnull)values;
- (void)removeCalls:(NSSet * _Nonnull)values;
@end

@class NSDictionary;
@class DBTripStatistics;

@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable arrivalAddress;
@property (nonatomic, copy) NSString * _Nullable arrivalCity;
@property (nonatomic, copy) NSString * _Nullable departureAddress;
@property (nonatomic, copy) NSString * _Nullable departureCity;
@property (nonatomic, copy) NSDate * _Nullable endDate;
@property (nonatomic, copy) NSString * _Nullable itinId;
@property (nonatomic, strong) NSDictionary * _Nullable metadata;
@property (nonatomic) BOOL safetyEventsSynced;
@property (nonatomic, copy) NSDate * _Nullable startDate;
@property (nonatomic) int32_t transportationMode;
@property (nonatomic) BOOL unscored;
@property (nonatomic, copy) NSString * _Nullable vehicleId;
@property (nonatomic, strong) NSSet * _Nullable advancedEnergyEstimation;
@property (nonatomic, strong) DBBrakeWear * _Nullable brakeWear;
@property (nonatomic, strong) NSSet * _Nullable calls;
@property (nonatomic, strong) DBDeclaredTransportationMode * _Nullable declaredTransportationMode;
@property (nonatomic, strong) DBDriverDistraction * _Nullable driverDistraction;
@property (nonatomic, strong) DBEcoDriving * _Nullable ecoDriving;
@property (nonatomic, strong) NSSet * _Nullable ecoDrivingContexts;
@property (nonatomic, strong) DBEnergyEstimation * _Nullable energyEstimation;
@property (nonatomic, strong) DBEvaluation * _Nullable evaluation;
@property (nonatomic, strong) DBFuelEstimation * _Nullable fuelEstimation;
@property (nonatomic, strong) NSSet * _Nullable fuelEstimationContexts;
@property (nonatomic, strong) DBLogbook * _Nullable logbook;
@property (nonatomic, strong) DBManeuver * _Nullable maneuver;
@property (nonatomic, strong) DBPollutants * _Nullable pollutants;
@property (nonatomic, strong) DBSafety * _Nullable safety;
@property (nonatomic, strong) NSSet * _Nullable safetyContexts;
@property (nonatomic, strong) NSSet * _Nullable safetyEvents;
@property (nonatomic, strong) DBSpeedingStatistics * _Nullable speedingStatistics;
@property (nonatomic, strong) NSSet * _Nullable speedLimitContexts;
@property (nonatomic, strong) DBTireWear * _Nullable tireWear;
@property (nonatomic, strong) NSSet * _Nullable tripAdvices;
@property (nonatomic, strong) DBTripStatistics * _Nullable tripStatistics;
@end


SWIFT_CLASS_NAMED("DBTripAdvice")
@interface DBTripAdvice : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface DBTripAdvice (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic) int32_t evaluation;
@property (nonatomic) int32_t feedback;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable messageId;
@property (nonatomic, copy) NSString * _Nullable theme;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBTripStatistics")
@interface DBTripStatistics : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBTripStatistics (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) BOOL day;
@property (nonatomic) double distance;
@property (nonatomic) double drivingDuration;
@property (nonatomic) double drivingPercentage;
@property (nonatomic) double duration;
@property (nonatomic) double idlingDuration;
@property (nonatomic) double idlingPercentage;
@property (nonatomic) int32_t meteo;
@property (nonatomic) double speedMean;
@property (nonatomic) int32_t subdispNb;
@property (nonatomic) BOOL weekDay;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule26DKAdvancedEnergyEstimation")
@interface DKAdvancedEnergyEstimation : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule11DKBrakeWear")
@interface DKBrakeWear : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule6DKCall")
@interface DKCall : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum DKContext : NSInteger;
enum DKWeather : NSInteger;

SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule15DKConditionData")
@interface DKConditionData : NSObject
@property (nonatomic, readonly) BOOL dayTimeTrip;
@property (nonatomic, readonly) BOOL weekDay;
@property (nonatomic, readonly) enum DKContext context;
@property (nonatomic, readonly) enum DKWeather weather;
- (nonnull instancetype)initWithDayTimeTrip:(BOOL)dayTimeTrip weekDay:(BOOL)weekDay context:(enum DKContext)context weather:(enum DKWeather)weather OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DKContext, open) {
  DKContextUnknown = 0,
  DKContextHeavyUrban = 1,
  DKContextUrban = 2,
  DKContextExtraUrban = 3,
  DKContextExpressWay = 4,
};


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule28DKDeclaredTransportationMode")
@interface DKDeclaredTransportationMode : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule19DKDriverDistraction")
@interface DKDriverDistraction : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule12DKEcoDriving")
@interface DKEcoDriving : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule19DKEcoDrivingContext")
@interface DKEcoDrivingContext : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule18DKEnergyEstimation")
@interface DKEnergyEstimation : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule12DKEvaluation")
@interface DKEvaluation : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule16DKEvaluationData")
@interface DKEvaluationData : NSObject
@property (nonatomic, readonly) NSInteger evaluation;
@property (nonatomic, readonly, copy) NSString * _Nullable comment;
- (nonnull instancetype)initWithEvaluation:(NSInteger)evaluation comment:(NSString * _Nullable)comment OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule16DKFuelEstimation")
@interface DKFuelEstimation : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule23DKFuelEstimationContext")
@interface DKFuelEstimationContext : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule17DKInformationData")
@interface DKInformationData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull departureCity;
@property (nonatomic, readonly, copy) NSString * _Nonnull arrivalCity;
@property (nonatomic, readonly, copy) NSString * _Nonnull departureAddress;
@property (nonatomic, readonly, copy) NSString * _Nonnull arrivalAddress;
@property (nonatomic, readonly, copy) NSDate * _Nonnull startDate;
@property (nonatomic, readonly) double departureLatitude;
@property (nonatomic, readonly) double departureLongitude;
@property (nonatomic, readonly) double arrivalLatitude;
@property (nonatomic, readonly) double arrivalLongitude;
@property (nonatomic, readonly) double distance;
@property (nonatomic, readonly) NSInteger duration;
- (nonnull instancetype)initWithDepartureCity:(NSString * _Nonnull)departureCity arrivalCity:(NSString * _Nonnull)arrivalCity departureAddress:(NSString * _Nonnull)departureAddress arrivalAddress:(NSString * _Nonnull)arrivalAddress startDate:(NSDate * _Nonnull)startDate departureLatitude:(double)departureLatitude departureLongitude:(double)departureLongitude arrivalLatitude:(double)arrivalLatitude arrivalLongitude:(double)arrivalLongitude distance:(double)distance duration:(NSInteger)duration OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule9DKLogbook")
@interface DKLogbook : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule10DKManeuver")
@interface DKManeuver : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule14DKManeuverData")
@interface DKManeuverData : NSObject
@property (nonatomic, readonly) NSInteger nbStraightReverseDrivings;
@property (nonatomic, readonly) NSInteger nbCurveReverseDrivings;
@property (nonatomic, readonly) NSInteger nbTurns;
@property (nonatomic, readonly) NSInteger nbHillStarts;
@property (nonatomic, readonly) NSInteger nbRoundAbouts;
@property (nonatomic, readonly) NSInteger nbEmergencyStops;
@property (nonatomic, readonly) NSInteger nbAngledParkings;
@property (nonatomic, readonly) NSInteger nbParallelParkings;
@property (nonatomic, readonly) NSInteger nbBayParkings;
- (nonnull instancetype)initWithNbStraightReverseDrivings:(NSInteger)nbStraightReverseDrivings nbCurveReverseDrivings:(NSInteger)nbCurveReverseDrivings nbTurns:(NSInteger)nbTurns nbHillStarts:(NSInteger)nbHillStarts nbRoundAbouts:(NSInteger)nbRoundAbouts nbEmergencyStops:(NSInteger)nbEmergencyStops nbAngledParkings:(NSInteger)nbAngledParkings nbParallelParkings:(NSInteger)nbParallelParkings nbBayParkings:(NSInteger)nbBayParkings OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule12DKManualTrip")
@interface DKManualTrip : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull tripId;
@property (nonatomic, readonly, strong) DKManeuverData * _Nonnull maneuver;
@property (nonatomic, readonly, strong) DKEvaluationData * _Nonnull evaluation;
@property (nonatomic, readonly, strong) DKInformationData * _Nonnull information;
@property (nonatomic, readonly, strong) DKConditionData * _Nonnull condition;
- (nonnull instancetype)initWithTripId:(NSString * _Nonnull)tripId maneuver:(DKManeuverData * _Nonnull)maneuver evaluation:(DKEvaluationData * _Nonnull)evaluation information:(DKInformationData * _Nonnull)information condition:(DKConditionData * _Nonnull)condition OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule12DKPollutants")
@interface DKPollutants : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DKRoadContext, open) {
  DKRoadContextTrafficJam = 0,
  DKRoadContextHeavyUrbanTraffic = 1,
  DKRoadContextCity = 2,
  DKRoadContextSuburban = 3,
  DKRoadContextExpressways = 4,
};


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule7DKRoute")
@interface DKRoute : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule8DKSafety")
@interface DKSafety : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule15DKSafetyContext")
@interface DKSafetyContext : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule14DKSafetyEvents")
@interface DKSafetyEvents : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule19DKSpeedLimitContext")
@interface DKSpeedLimitContext : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule20DKSpeedingStatistics")
@interface DKSpeedingStatistics : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DKSynthesisType, open) {
  DKSynthesisTypeDistance = 0,
  DKSynthesisTypeEfficiency = 1,
  DKSynthesisTypePhoneDistraction = 2,
  DKSynthesisTypeSafety = 3,
  DKSynthesisTypeSpeeding = 4,
};


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule10DKTireWear")
@interface DKTireWear : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule6DKTrip")
@interface DKTrip : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule12DKTripAdvice")
@interface DKTripAdvice : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule16DKTripStatistics")
@interface DKTripStatistics : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DKWeather, open) {
  DKWeatherUnknown = 0,
  DKWeatherSun = 1,
  DKWeatherCloud = 2,
  DKWeatherFog = 3,
  DKWeatherRain = 4,
  DKWeatherSnow = 5,
  DKWeatherIce = 6,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef DRIVEKITDBTRIPACCESSMODULE_SWIFT_H
#define DRIVEKITDBTRIPACCESSMODULE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DriveKitDBTripAccessModule",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("DBAdvancedEnergyEstimation")
@interface DBAdvancedEnergyEstimation : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class DBTrip;

@interface DBAdvancedEnergyEstimation (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t contextId;
@property (nonatomic) double distance;
@property (nonatomic) double duration;
@property (nonatomic) double energy;
@property (nonatomic) double energyConsumption;
@property (nonatomic) double energyOpti;
@property (nonatomic) double energyOptiConsumption;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBBrakeWear")
@interface DBBrakeWear : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBBrakeWear (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t frontBrakeAutonomy;
@property (nonatomic) int32_t frontBrakeDistance;
@property (nonatomic) int32_t frontBrakePadWear;
@property (nonatomic) int32_t frontBrakeTotalWear;
@property (nonatomic) int32_t frontBrakeWearRate;
@property (nonatomic) int32_t rearBrakeAutonomy;
@property (nonatomic) int32_t rearBrakeDistance;
@property (nonatomic) int32_t rearBrakePadWear;
@property (nonatomic) int32_t rearBrakeTotalWear;
@property (nonatomic) int32_t rearBrakeWearRate;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBCall")
@interface DBCall : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class NSString;

@interface DBCall (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable audioInput;
@property (nonatomic, copy) NSString * _Nullable audioName;
@property (nonatomic, copy) NSString * _Nullable audioOutput;
@property (nonatomic, copy) NSString * _Nullable audioSystemValue;
@property (nonatomic) int32_t bluetoothClass;
@property (nonatomic) int32_t distance;
@property (nonatomic) int16_t distancePercent;
@property (nonatomic) int32_t duration;
@property (nonatomic) int16_t durationPercent;
@property (nonatomic) double end;
@property (nonatomic) int32_t id;
@property (nonatomic) BOOL isForbidden;
@property (nonatomic) double start;
@property (nonatomic, copy) NSString * _Nullable typeValue;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBCondition")
@interface DBCondition : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class DBManualTrip;

@interface DBCondition (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int16_t context;
@property (nonatomic) BOOL dayTimeTrip;
@property (nonatomic) int16_t weather;
@property (nonatomic) BOOL weekDay;
@property (nonatomic, strong) DBManualTrip * _Nullable trip;
@end


SWIFT_CLASS_NAMED("DBDeclaredTransportationMode")
@interface DBDeclaredTransportationMode : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBDeclaredTransportationMode (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic) BOOL passenger;
@property (nonatomic) int32_t transportationMode;
@property (nonatomic, strong) DBTrip * _Nullable trip;
@end


SWIFT_CLASS_NAMED("DBDriverDistraction")
@interface DBDriverDistraction : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class NSNumber;

@interface DBDriverDistraction (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) double distancePercentUnlock;
@property (nonatomic) double distanceUnlock;
@property (nonatomic) double durationPercentUnlock;
@property (nonatomic) double durationUnlock;
@property (nonatomic) int32_t nbUnlock;
@property (nonatomic) double score;
@property (nonatomic, strong) NSNumber * _Nullable scoreCallNumber;
@property (nonatomic, strong) NSNumber * _Nullable scoreUnlockNumber;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBEcoDriving")
@interface DBEcoDriving : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBEcoDriving (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t energyClass;
@property (nonatomic) double score;
@property (nonatomic) double scoreAccel;
@property (nonatomic) double scoreDecel;
@property (nonatomic) double scoreMain;
@property (nonatomic) double stdDevAccel;
@property (nonatomic) double stdDevDecel;
@property (nonatomic) double stdDevMain;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBEcoDrivingContext")
@interface DBEcoDrivingContext : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBEcoDrivingContext (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t contextId;
@property (nonatomic) double distance;
@property (nonatomic) double duration;
@property (nonatomic) double efficiencyScore;
@property (nonatomic) double scoreAccel;
@property (nonatomic) double scoreDecel;
@property (nonatomic) double scoreMain;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBEnergyEstimation")
@interface DBEnergyEstimation : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBEnergyEstimation (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) double energy;
@property (nonatomic) double energyConsumption;
@property (nonatomic) double energyOpti;
@property (nonatomic) double energyOptiConsumption;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBEvaluation")
@interface DBEvaluation : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface DBEvaluation (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic) int32_t evaluation;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBFuelEstimation")
@interface DBFuelEstimation : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBFuelEstimation (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) double co2Emission;
@property (nonatomic) double co2Mass;
@property (nonatomic) double coldFuelVolume;
@property (nonatomic) BOOL engineTempStatus;
@property (nonatomic) double fuelConsumption;
@property (nonatomic) double fuelVolume;
@property (nonatomic) double idleCo2Emission;
@property (nonatomic) double idleCo2Mass;
@property (nonatomic) double idleFuelConsumption;
@property (nonatomic) double idleFuelPercentage;
@property (nonatomic) double idleFuelVolume;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBFuelEstimationContext")
@interface DBFuelEstimationContext : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBFuelEstimationContext (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) double co2Emission;
@property (nonatomic) double co2Mass;
@property (nonatomic) int32_t contextId;
@property (nonatomic) double distance;
@property (nonatomic) double duration;
@property (nonatomic) double fuelConsumption;
@property (nonatomic) double fuelVolume;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBInformation")
@interface DBInformation : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class NSDate;

@interface DBInformation (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable arrivalAddress;
@property (nonatomic, copy) NSString * _Nullable arrivalCity;
@property (nonatomic) double arrivalLatitude;
@property (nonatomic) double arrivalLongitude;
@property (nonatomic, copy) NSString * _Nullable departureAddress;
@property (nonatomic, copy) NSString * _Nullable departureCity;
@property (nonatomic) double departureLatitude;
@property (nonatomic) double departureLongitude;
@property (nonatomic) double distance;
@property (nonatomic) int32_t duration;
@property (nonatomic, copy) NSDate * _Nullable startDate;
@property (nonatomic, strong) DBManualTrip * _Nullable trip;
@end


SWIFT_CLASS_NAMED("DBLogbook")
@interface DBLogbook : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBLogbook (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t status;
@property (nonatomic, copy) NSDate * _Nullable updateDate;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBManeuver")
@interface DBManeuver : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface DBManeuver (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t nbAngledParkings;
@property (nonatomic) int32_t nbBayParkings;
@property (nonatomic) int32_t nbCurveReverseDrivings;
@property (nonatomic) int32_t nbEmergencyStops;
@property (nonatomic) int32_t nbHillStarts;
@property (nonatomic) int32_t nbParallelParkings;
@property (nonatomic) int32_t nbRoundAbouts;
@property (nonatomic) int32_t nbStraightReverseDrivings;
@property (nonatomic) int32_t nbTurns;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBManualEvaluation")
@interface DBManualEvaluation : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBManualEvaluation (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic) int32_t evaluation;
@property (nonatomic, strong) DBManualTrip * _Nullable trip;
@end


SWIFT_CLASS_NAMED("DBManualManeuver")
@interface DBManualManeuver : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBManualManeuver (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t nbAngledParkings;
@property (nonatomic) int32_t nbBayParkings;
@property (nonatomic) int32_t nbCurveReverseDrivings;
@property (nonatomic) int32_t nbEmergencyStops;
@property (nonatomic) int32_t nbHillStarts;
@property (nonatomic) int32_t nbParallelParkings;
@property (nonatomic) int32_t nbRoundAbouts;
@property (nonatomic) int32_t nbStraightReverseDrivings;
@property (nonatomic) int32_t nbTurns;
@property (nonatomic, strong) DBManualTrip * _Nullable trip;
@end


SWIFT_CLASS_NAMED("DBManualTrip")
@interface DBManualTrip : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface DBManualTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable tripId;
@property (nonatomic, strong) DBCondition * _Nullable condition;
@property (nonatomic, strong) DBManualEvaluation * _Nullable evaluation;
@property (nonatomic, strong) DBInformation * _Nullable information;
@property (nonatomic, strong) DBManualManeuver * _Nullable maneuver;
@end


SWIFT_CLASS_NAMED("DBPollutants")
@interface DBPollutants : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBPollutants (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) double co;
@property (nonatomic) double hc;
@property (nonatomic) double nox;
@property (nonatomic) double soot;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBRoute")
@interface DBRoute : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class NSArray;

@interface DBRoute (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, strong) NSArray * _Nullable callIndex;
@property (nonatomic, strong) NSArray * _Nullable callTime;
@property (nonatomic, copy) NSString * _Nullable itinId;
@property (nonatomic, strong) NSArray * _Nullable latitude;
@property (nonatomic, strong) NSArray * _Nullable longitude;
@property (nonatomic, strong) NSArray * _Nullable screenLockedIndex;
@property (nonatomic, strong) NSArray * _Nullable screenLockedTime;
@property (nonatomic, strong) NSArray * _Nullable screenStatus;
@property (nonatomic, strong) NSArray * _Nullable speedingIndex;
@property (nonatomic, strong) NSArray * _Nullable speedingTime;
@end


SWIFT_CLASS_NAMED("DBSafety")
@interface DBSafety : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBSafety (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t nbAccel;
@property (nonatomic) int32_t nbAccelCrit;
@property (nonatomic) int32_t nbAdh;
@property (nonatomic) int32_t nbAdhCrit;
@property (nonatomic) int32_t nbDecel;
@property (nonatomic) int32_t nbDecelCrit;
@property (nonatomic) double safetyScore;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBSafetyContext")
@interface DBSafetyContext : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBSafetyContext (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t contextId;
@property (nonatomic) double distance;
@property (nonatomic) double duration;
@property (nonatomic) int32_t nbAccel;
@property (nonatomic) int32_t nbAccelCrit;
@property (nonatomic) int32_t nbAdh;
@property (nonatomic) int32_t nbAdhCrit;
@property (nonatomic) int32_t nbDecel;
@property (nonatomic) int32_t nbDecelCrit;
@property (nonatomic) double safetyScore;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBSafetyEvents")
@interface DBSafetyEvents : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBSafetyEvents (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) double distance;
@property (nonatomic) double elevation;
@property (nonatomic) double heading;
@property (nonatomic) double latitude;
@property (nonatomic) int32_t level;
@property (nonatomic) double longitude;
@property (nonatomic) double time;
@property (nonatomic) int32_t type;
@property (nonatomic) double value;
@property (nonatomic) double velocity;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBSpeedLimitContext")
@interface DBSpeedLimitContext : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBSpeedLimitContext (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t distance;
@property (nonatomic) int32_t duration;
@property (nonatomic) double score;
@property (nonatomic) int32_t speedingDistance;
@property (nonatomic) int32_t speedingDuration;
@property (nonatomic) int32_t speedLimit;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBSpeedingStatistics")
@interface DBSpeedingStatistics : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBSpeedingStatistics (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t distance;
@property (nonatomic) int32_t duration;
@property (nonatomic) double score;
@property (nonatomic) int32_t speedingDistance;
@property (nonatomic) int32_t speedingDuration;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBTireWear")
@interface DBTireWear : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBTireWear (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) int32_t frontTireAutonomy;
@property (nonatomic) int32_t frontTireDistance;
@property (nonatomic) int32_t frontTireTotalWear;
@property (nonatomic) int32_t frontTireWear;
@property (nonatomic) int32_t frontTireWearRate;
@property (nonatomic) int32_t rearTireAutonomy;
@property (nonatomic) int32_t rearTireDistance;
@property (nonatomic) int32_t rearTireTotalWear;
@property (nonatomic) int32_t rearTireWear;
@property (nonatomic) int32_t rearTireWearRate;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBTrip")
@interface DBTrip : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@class DBTripAdvice;
@class NSSet;

@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addTripAdvicesObject:(DBTripAdvice * _Nonnull)value;
- (void)removeTripAdvicesObject:(DBTripAdvice * _Nonnull)value;
- (void)addTripAdvices:(NSSet * _Nonnull)values;
- (void)removeTripAdvices:(NSSet * _Nonnull)values;
@end


@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addSpeedLimitContextsObject:(DBSpeedLimitContext * _Nonnull)value;
- (void)removeSpeedLimitContextsObject:(DBSpeedLimitContext * _Nonnull)value;
- (void)addSpeedLimitContexts:(NSSet * _Nonnull)values;
- (void)removeSpeedLimitContexts:(NSSet * _Nonnull)values;
@end


@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addSafetyEventsObject:(DBSafetyEvents * _Nonnull)value;
- (void)removeSafetyEventsObject:(DBSafetyEvents * _Nonnull)value;
- (void)addSafetyEvents:(NSSet * _Nonnull)values;
- (void)removeSafetyEvents:(NSSet * _Nonnull)values;
@end


@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addSafetyContextsObject:(DBSafetyContext * _Nonnull)value;
- (void)removeSafetyContextsObject:(DBSafetyContext * _Nonnull)value;
- (void)addSafetyContexts:(NSSet * _Nonnull)values;
- (void)removeSafetyContexts:(NSSet * _Nonnull)values;
@end


@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addFuelEstimationContextsObject:(DBFuelEstimationContext * _Nonnull)value;
- (void)removeFuelEstimationContextsObject:(DBFuelEstimationContext * _Nonnull)value;
- (void)addFuelEstimationContexts:(NSSet * _Nonnull)values;
- (void)removeFuelEstimationContexts:(NSSet * _Nonnull)values;
@end


@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addEcoDrivingContextsObject:(DBEcoDrivingContext * _Nonnull)value;
- (void)removeEcoDrivingContextsObject:(DBEcoDrivingContext * _Nonnull)value;
- (void)addEcoDrivingContexts:(NSSet * _Nonnull)values;
- (void)removeEcoDrivingContexts:(NSSet * _Nonnull)values;
@end


@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addAdvancedEnergyEstimationObject:(DBAdvancedEnergyEstimation * _Nonnull)value;
- (void)removeAdvancedEnergyEstimationObject:(DBAdvancedEnergyEstimation * _Nonnull)value;
- (void)addAdvancedEnergyEstimation:(NSSet * _Nonnull)values;
- (void)removeAdvancedEnergyEstimation:(NSSet * _Nonnull)values;
@end


@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
- (void)addCallsObject:(DBCall * _Nonnull)value;
- (void)removeCallsObject:(DBCall * _Nonnull)value;
- (void)addCalls:(NSSet * _Nonnull)values;
- (void)removeCalls:(NSSet * _Nonnull)values;
@end

@class NSDictionary;
@class DBTripStatistics;

@interface DBTrip (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable arrivalAddress;
@property (nonatomic, copy) NSString * _Nullable arrivalCity;
@property (nonatomic, copy) NSString * _Nullable departureAddress;
@property (nonatomic, copy) NSString * _Nullable departureCity;
@property (nonatomic, copy) NSDate * _Nullable endDate;
@property (nonatomic, copy) NSString * _Nullable itinId;
@property (nonatomic, strong) NSDictionary * _Nullable metadata;
@property (nonatomic) BOOL safetyEventsSynced;
@property (nonatomic, copy) NSDate * _Nullable startDate;
@property (nonatomic) int32_t transportationMode;
@property (nonatomic) BOOL unscored;
@property (nonatomic, copy) NSString * _Nullable vehicleId;
@property (nonatomic, strong) NSSet * _Nullable advancedEnergyEstimation;
@property (nonatomic, strong) DBBrakeWear * _Nullable brakeWear;
@property (nonatomic, strong) NSSet * _Nullable calls;
@property (nonatomic, strong) DBDeclaredTransportationMode * _Nullable declaredTransportationMode;
@property (nonatomic, strong) DBDriverDistraction * _Nullable driverDistraction;
@property (nonatomic, strong) DBEcoDriving * _Nullable ecoDriving;
@property (nonatomic, strong) NSSet * _Nullable ecoDrivingContexts;
@property (nonatomic, strong) DBEnergyEstimation * _Nullable energyEstimation;
@property (nonatomic, strong) DBEvaluation * _Nullable evaluation;
@property (nonatomic, strong) DBFuelEstimation * _Nullable fuelEstimation;
@property (nonatomic, strong) NSSet * _Nullable fuelEstimationContexts;
@property (nonatomic, strong) DBLogbook * _Nullable logbook;
@property (nonatomic, strong) DBManeuver * _Nullable maneuver;
@property (nonatomic, strong) DBPollutants * _Nullable pollutants;
@property (nonatomic, strong) DBSafety * _Nullable safety;
@property (nonatomic, strong) NSSet * _Nullable safetyContexts;
@property (nonatomic, strong) NSSet * _Nullable safetyEvents;
@property (nonatomic, strong) DBSpeedingStatistics * _Nullable speedingStatistics;
@property (nonatomic, strong) NSSet * _Nullable speedLimitContexts;
@property (nonatomic, strong) DBTireWear * _Nullable tireWear;
@property (nonatomic, strong) NSSet * _Nullable tripAdvices;
@property (nonatomic, strong) DBTripStatistics * _Nullable tripStatistics;
@end


SWIFT_CLASS_NAMED("DBTripAdvice")
@interface DBTripAdvice : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface DBTripAdvice (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic) int32_t evaluation;
@property (nonatomic) int32_t feedback;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable messageId;
@property (nonatomic, copy) NSString * _Nullable theme;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS_NAMED("DBTripStatistics")
@interface DBTripStatistics : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface DBTripStatistics (SWIFT_EXTENSION(DriveKitDBTripAccessModule))
@property (nonatomic) BOOL day;
@property (nonatomic) double distance;
@property (nonatomic) double drivingDuration;
@property (nonatomic) double drivingPercentage;
@property (nonatomic) double duration;
@property (nonatomic) double idlingDuration;
@property (nonatomic) double idlingPercentage;
@property (nonatomic) int32_t meteo;
@property (nonatomic) double speedMean;
@property (nonatomic) int32_t subdispNb;
@property (nonatomic) BOOL weekDay;
@property (nonatomic, strong) DBTrip * _Nullable itinerary;
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule26DKAdvancedEnergyEstimation")
@interface DKAdvancedEnergyEstimation : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule11DKBrakeWear")
@interface DKBrakeWear : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule6DKCall")
@interface DKCall : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum DKContext : NSInteger;
enum DKWeather : NSInteger;

SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule15DKConditionData")
@interface DKConditionData : NSObject
@property (nonatomic, readonly) BOOL dayTimeTrip;
@property (nonatomic, readonly) BOOL weekDay;
@property (nonatomic, readonly) enum DKContext context;
@property (nonatomic, readonly) enum DKWeather weather;
- (nonnull instancetype)initWithDayTimeTrip:(BOOL)dayTimeTrip weekDay:(BOOL)weekDay context:(enum DKContext)context weather:(enum DKWeather)weather OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DKContext, open) {
  DKContextUnknown = 0,
  DKContextHeavyUrban = 1,
  DKContextUrban = 2,
  DKContextExtraUrban = 3,
  DKContextExpressWay = 4,
};


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule28DKDeclaredTransportationMode")
@interface DKDeclaredTransportationMode : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule19DKDriverDistraction")
@interface DKDriverDistraction : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule12DKEcoDriving")
@interface DKEcoDriving : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule19DKEcoDrivingContext")
@interface DKEcoDrivingContext : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule18DKEnergyEstimation")
@interface DKEnergyEstimation : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule12DKEvaluation")
@interface DKEvaluation : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule16DKEvaluationData")
@interface DKEvaluationData : NSObject
@property (nonatomic, readonly) NSInteger evaluation;
@property (nonatomic, readonly, copy) NSString * _Nullable comment;
- (nonnull instancetype)initWithEvaluation:(NSInteger)evaluation comment:(NSString * _Nullable)comment OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule16DKFuelEstimation")
@interface DKFuelEstimation : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule23DKFuelEstimationContext")
@interface DKFuelEstimationContext : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule17DKInformationData")
@interface DKInformationData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull departureCity;
@property (nonatomic, readonly, copy) NSString * _Nonnull arrivalCity;
@property (nonatomic, readonly, copy) NSString * _Nonnull departureAddress;
@property (nonatomic, readonly, copy) NSString * _Nonnull arrivalAddress;
@property (nonatomic, readonly, copy) NSDate * _Nonnull startDate;
@property (nonatomic, readonly) double departureLatitude;
@property (nonatomic, readonly) double departureLongitude;
@property (nonatomic, readonly) double arrivalLatitude;
@property (nonatomic, readonly) double arrivalLongitude;
@property (nonatomic, readonly) double distance;
@property (nonatomic, readonly) NSInteger duration;
- (nonnull instancetype)initWithDepartureCity:(NSString * _Nonnull)departureCity arrivalCity:(NSString * _Nonnull)arrivalCity departureAddress:(NSString * _Nonnull)departureAddress arrivalAddress:(NSString * _Nonnull)arrivalAddress startDate:(NSDate * _Nonnull)startDate departureLatitude:(double)departureLatitude departureLongitude:(double)departureLongitude arrivalLatitude:(double)arrivalLatitude arrivalLongitude:(double)arrivalLongitude distance:(double)distance duration:(NSInteger)duration OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule9DKLogbook")
@interface DKLogbook : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule10DKManeuver")
@interface DKManeuver : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule14DKManeuverData")
@interface DKManeuverData : NSObject
@property (nonatomic, readonly) NSInteger nbStraightReverseDrivings;
@property (nonatomic, readonly) NSInteger nbCurveReverseDrivings;
@property (nonatomic, readonly) NSInteger nbTurns;
@property (nonatomic, readonly) NSInteger nbHillStarts;
@property (nonatomic, readonly) NSInteger nbRoundAbouts;
@property (nonatomic, readonly) NSInteger nbEmergencyStops;
@property (nonatomic, readonly) NSInteger nbAngledParkings;
@property (nonatomic, readonly) NSInteger nbParallelParkings;
@property (nonatomic, readonly) NSInteger nbBayParkings;
- (nonnull instancetype)initWithNbStraightReverseDrivings:(NSInteger)nbStraightReverseDrivings nbCurveReverseDrivings:(NSInteger)nbCurveReverseDrivings nbTurns:(NSInteger)nbTurns nbHillStarts:(NSInteger)nbHillStarts nbRoundAbouts:(NSInteger)nbRoundAbouts nbEmergencyStops:(NSInteger)nbEmergencyStops nbAngledParkings:(NSInteger)nbAngledParkings nbParallelParkings:(NSInteger)nbParallelParkings nbBayParkings:(NSInteger)nbBayParkings OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule12DKManualTrip")
@interface DKManualTrip : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull tripId;
@property (nonatomic, readonly, strong) DKManeuverData * _Nonnull maneuver;
@property (nonatomic, readonly, strong) DKEvaluationData * _Nonnull evaluation;
@property (nonatomic, readonly, strong) DKInformationData * _Nonnull information;
@property (nonatomic, readonly, strong) DKConditionData * _Nonnull condition;
- (nonnull instancetype)initWithTripId:(NSString * _Nonnull)tripId maneuver:(DKManeuverData * _Nonnull)maneuver evaluation:(DKEvaluationData * _Nonnull)evaluation information:(DKInformationData * _Nonnull)information condition:(DKConditionData * _Nonnull)condition OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule12DKPollutants")
@interface DKPollutants : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DKRoadContext, open) {
  DKRoadContextTrafficJam = 0,
  DKRoadContextHeavyUrbanTraffic = 1,
  DKRoadContextCity = 2,
  DKRoadContextSuburban = 3,
  DKRoadContextExpressways = 4,
};


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule7DKRoute")
@interface DKRoute : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule8DKSafety")
@interface DKSafety : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule15DKSafetyContext")
@interface DKSafetyContext : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule14DKSafetyEvents")
@interface DKSafetyEvents : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule19DKSpeedLimitContext")
@interface DKSpeedLimitContext : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule20DKSpeedingStatistics")
@interface DKSpeedingStatistics : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DKSynthesisType, open) {
  DKSynthesisTypeDistance = 0,
  DKSynthesisTypeEfficiency = 1,
  DKSynthesisTypePhoneDistraction = 2,
  DKSynthesisTypeSafety = 3,
  DKSynthesisTypeSpeeding = 4,
};


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule10DKTireWear")
@interface DKTireWear : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule6DKTrip")
@interface DKTrip : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule12DKTripAdvice")
@interface DKTripAdvice : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC26DriveKitDBTripAccessModule16DKTripStatistics")
@interface DKTripStatistics : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DKWeather, open) {
  DKWeatherUnknown = 0,
  DKWeatherSun = 1,
  DKWeatherCloud = 2,
  DKWeatherFog = 3,
  DKWeatherRain = 4,
  DKWeatherSnow = 5,
  DKWeatherIce = 6,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
